### PR TITLE
Data Viz

### PR DESCRIPTION
**Pull request by rviscomi**
Features:
- [x] simplified timeseries
  - improved tooltip
- [x] fixes [infinity bug (#25)](https://github.com/HTTPArchive/beta.httparchive.org/issues/25)
- [x] simplified histogram
  - outliers > 95% CDF are hidden by default
  - CDF hidden from legend and tooltip
- [x] show/hide CDF when desktop/mobile histogram series shown/hidden
- [x] the singularity is here: eg fix "1 libraries" grammar to "1 library"
- [x] [security policy](https://github.com/GoogleCloudPlatform/flask-talisman) (forced https, csp, hsts, etc)

Progress on #13

image

image

image

### CODE REVIEW

**Comment by rviscomi** [comment]
@igrigorik ping -- mostly just looking for feedback on the data viz tooltips, no need for a gritty code review

You can test drive these changes on the staging app: https://httparchive-staging.appspot.com/

**Comment by igrigorik** [comment]
Nice work Rick! One thing that is lost in this update is the CDF values on the histogram..

image

Perhaps this is counter to what you're aiming for here (simplify), but it would be nice if we could somehow persist / communicate that info in the histogram tooltip. WDYT?

**Comment by rviscomi** [comment]
Yeah I had a hard time thinking of a way to include it cleanly without adding confusion.

Maybe use the summation symbol ∑ to indicate CDF, in the same kind of design that we use to show change over time in the timeseries summaries:

image

image


WDYT?

**Comment by igrigorik** [comment]
∑ is not commonly understand symbol for CDF, and afaik I don't think there is one. The best I can come up with is still stick with "CDF: x" but in small text.. =/

**Comment by rviscomi** [comment]
Here's a revision that includes CDF. Using the word "Cumulative" here to avoid jargon. WDYT?
image

**Comment by igrigorik** [comment]
^^ 👍 👍 

Ship it.

**Comment by rviscomi** [comment]
Woohoo! 5/8 of the [graduation checklist](https://github.com/HTTPArchive/beta.httparchive.org/issues/13) completed! 🎉

**Pull request merged**
